const fs = require('fs');
const { join } = require('path');
const { execSync } = require('child_process');

(() => {
  try {
    const testingCode = 'aW1wb3J0ICogYXMgYXNzZXJ0IGZyb20gJ2Fzc2VydCc7CmltcG9ydCAqIGFzIGZzIGZyb20gJ2ZzJzsKaW1wb3J0ICogYXMgY3AgZnJvbSAnY2hpbGRfcHJvY2Vzcyc7CgooYXN5bmMgKCkgPT4gewogIC8vIHRlc3RpbmcgdW53b3JkIGFuZCByZXdvcmQKICBjb25zdCB7IHVud29yZCwgcmV3b3JkIH0gPSBhd2FpdCBpbXBvcnQoJy4vdXRpbHMuanMnKTsKCiAgLy8gY2hlY2sgaWYgdW53b3JkIGFuZCByZXdvcmQgaXMgYSBmdW5jdGlvbgogIGFzc2VydC5lcXVhbCh0eXBlb2YgdW53b3JkLCAnZnVuY3Rpb24nLCAnS2FtdSBoYXJ1cyBtZW5nZWtzcG9yIGZ1bmdzaSBgdW53b3JkYCBzZWNhcmEgYG5hbWVkIGV4cG9ydGAuIFNpbWFrIG1hdGVyaSAiaHR0cHM6Ly93d3cuZGljb2RpbmcuY29tL2FjYWRlbWllcy82MTAvdHV0b3JpYWxzLzMzNTczIiB1bnR1ayBtZW5nZXRhaHVpIGNhcmEgaW1wb3IgZGFuIGVrc3BvciBuaWxhaSBkZW5nYW4gRVNNLicpOwogIGFzc2VydC5lcXVhbCh0eXBlb2YgcmV3b3JkLCAnZnVuY3Rpb24nLCAnS2FtdSBoYXJ1cyBtZW5nZWtzcG9yIGZ1bmdzaSBgcmV3b3JkYCBzZWNhcmEgYG5hbWVkIGV4cGVydGAuIFNpbWFrIG1hdGVyaSAiaHR0cHM6Ly93d3cuZGljb2RpbmcuY29tL2FjYWRlbWllcy82MTAvdHV0b3JpYWxzLzMzNTczIiB1bnR1ayBtZW5nZXRhaHVpIGNhcmEgaW1wb3IgZGFuIGVrc3BvciBuaWxhaSBkZW5nYW4gRVNNLicpOwoKICAvLyBjaGVjayBpZiB1bndvcmQgYW5kIHJld29yZCBpcyB3b3JraW5nCiAgYXNzZXJ0LmRlZXBFcXVhbCh1bndvcmQoJ0hlbGxvJyksICdIZWxsbycuc3BsaXQoJycpLCAnRnVuZ3NpIGB1bndvcmRgIHRpZGFrIGJlcmphbGFuIGRlbmdhbiBzZW1lc3RpbnlhLiBNb2hvbiB1bnR1ayBkaWNlayBsYWdpLCB5YSEgXl9eJyk7CiAgYXNzZXJ0LmVxdWFsKHJld29yZCgnSCcsICdlJywgJ2wnLCAnbCcsICdvJyksICdIZWxsbycsICdGdW5nc2kgYHJld29yZGAgdGlkYWsgYmVyamFsYW4gZGVuZ2FuIHNlbWVzdGlueWEuIE1vaG9uIHVudHVrIGRpY2VrIGxhZ2ksIHlhISBeX14nKTsKCiAgLy8gdGVzdGluZyBVbmlxdWVBcnJheQogIGNvbnN0IHsgZGVmYXVsdDogVW5pcXVlQXJyYXkgfSA9IGF3YWl0IGltcG9ydCgnLi9VbmlxdWVBcnJheS5qcycpOwoKICAvLyBjaGVjayBpZiBVbmlxdWVBcnJheSBpcyBhIGNsYXNzCiAgYXNzZXJ0LmVxdWFsKHR5cGVvZiBVbmlxdWVBcnJheSwgJ2Z1bmN0aW9uJywgJ0thbXUgaGFydXMgbWVuZ2Vrc3BvciBjbGFzcyBgVW5pcXVlQXJyYXlgIHNlY2FyYSAibGFuZ3N1bmciLiBTaW1hayBtYXRlcmkgImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zMzU3MyIgRm9ybWF0IFNpc3RlbSBNb2R1bGFyaXNhc2kgZGkgTm9kZS5qcyB1bnR1ayBtZW5nZXRhaHVpIGNhcmEgaW1wb3IgZGFuIGVrc3BvciBuaWxhaSBkZW5nYW4gRVNNLicpOwoKICAvLyBjaGVjayBpZiBVbmlxdWVBcnJheSBpcyB3b3JraW5nCiAgY29uc3QgdW5pcXVlSW50ZWdlcnMgPSBuZXcgVW5pcXVlQXJyYXkoMSwgMSwgMiwgMywgMywgNCwgNSwgNSk7CiAgYXNzZXJ0LmVxdWFsKHVuaXF1ZUludGVnZXJzLmxlbmd0aCwgNSwgJ0Z1bmdzaSBgVW5pcXVlQXJyYXlgIHRpZGFrIGJlcmphbGFuIGRlbmdhbiBzZW1lc3RpbnlhLiBTaWxha2FuIGRpY2VrIGxhZ2ksIHlhISBeX14nKTsKCiAgLy8gdGVzdGluZyBtYWluLmpzCiAgY29uc3QgYWRkaXRpb25hbENvZGVUb0JlQWRkID0gJ0NtbHRjRzl5ZENBcUlHRnpJR0Z6YzJWeWRDQWdabkp2YlNBbllYTnpaWEowSnpzS0NtRnpjMlZ5ZEM1bGNYVmhiQ2gwZVhCbGIyWWdkVzUzYjNKa0xDQW5ablZ1WTNScGIyNG5MQ0FuZVc5MUlHMTFjM1FnYVcxd2IzSjBJR1oxYm1OMGFXOXVJR0IxYm5kdmNtUmdKeWs3Q21GemMyVnlkQzVsY1hWaGJDaDBlWEJsYjJZZ2NtVjNiM0prTENBblpuVnVZM1JwYjI0bkxDQW5lVzkxSUcxMWMzUWdhVzF3YjNKMElHWjFibU4wYVc5dUlHQnlaWGR2Y21SZ0p5azdDbUZ6YzJWeWRDNWtaV1Z3UlhGMVlXd29kVzUzYjNKa0tDZElaV3hzYnljcExDQW5TR1ZzYkc4bkxuTndiR2wwS0NjbktTd2dKMkIxYm5kdmNtUmdJRzV2ZENCM2IzSnJhVzVuSUdGeklITjFjSEJ2YzJWa0lIUnZJR0psTGljcE93cGhjM05sY25RdVpYRjFZV3dvY21WM2IzSmtLQ2RJSnl3Z0oyVW5MQ0FuYkNjc0lDZHNKeXdnSjI4bktTd2dKMGhsYkd4dkp5d2dKMkJ5WlhkdmNtUmdJRzV2ZENCM2IzSnJhVzVuSUdGeklITjFjSEJ2YzJWa0lIUnZJR0psTGljcE93cGhjM05sY25RdVpYRjFZV3dvZEhsd1pXOW1JRlZ1YVhGMVpVRnljbUY1TENBblpuVnVZM1JwYjI0bkxDQW5lVzkxSUcxMWMzUWdJbVJwY21WamRHeDVJaUJwYlhCdmNuUWdZMnhoYzNNZ1lGVnVhWEYxWlVGeWNtRjVZQ2NwT3dwaGMzTmxjblF1WlhGMVlXd29ibVYzSUZWdWFYRjFaVUZ5Y21GNUtERXNJREVzSURJc0lETXNJRE1zSURRc0lEVXNJRFVwTG14bGJtZDBhQ3dnTlN3Z0oxVnVhWEYxWlVGeWNtRjVJR2x6SUc1dmRDQjNiM0pyYVc1bklHRnpJSE4xY0hCdmMyVmtJSFJ2SUdKbExpY3BPdz09JzsKICBjb25zdCBjdXJyZW50TWFpbkNvZGUgPSBmcy5yZWFkRmlsZVN5bmMoJy4vbWFpbi5qcycsICd1dGYtOCcpOwogIGNvbnN0IG5ld01haW5Db2RlID0gY3VycmVudE1haW5Db2RlICsgQnVmZmVyLmZyb20oYWRkaXRpb25hbENvZGVUb0JlQWRkLCAnYmFzZTY0JykudG9TdHJpbmcoJ3V0Zi04Jyk7CiAgZnMud3JpdGVGaWxlU3luYygnLi9tYWluLW5ldy5qcycsIG5ld01haW5Db2RlLCAndXRmLTgnKTsKCiAgLy8gY2hhbmdlIHBhY2thZ2UuanNvbiBzdGFydCBzY3JpcHQKICBjb25zdCBjdXJyZW50UGFja2FnZUpzb24gPSBmcy5yZWFkRmlsZVN5bmMoJy4vcGFja2FnZS5qc29uJywgJ3V0Zi04Jyk7CiAgY29uc3QgbmV3UGFja2FnZUpzb24gPSBjdXJyZW50UGFja2FnZUpzb24ucmVwbGFjZSgnbWFpbi5qcycsICdtYWluLW5ldy5qcycpOwogIGZzLndyaXRlRmlsZVN5bmMoJy4vcGFja2FnZS5qc29uJywgbmV3UGFja2FnZUpzb24sICd1dGYtOCcpOwoKICAvLyBjaGVjayBpZiBtYWluLmpzIGlzIHdvcmtpbmcKICBjb25zdCB7IHN0ZGVyciB9ID0gY3Auc3Bhd25TeW5jKAogICAgcHJvY2Vzcy5wbGF0Zm9ybSA9PT0gJ3dpbjMyJyA/ICducG0uY21kJyA6ICducG0nLCAKICAgIFsnc3RhcnQnXQogICk7CiAgY29uc3QgZXJyb3JTdHJpbmcgPSBzdGRlcnIudG9TdHJpbmcoKTsKICBmcy51bmxpbmtTeW5jKCcuL21haW4tbmV3LmpzJyk7CiAgYXNzZXJ0LmVxdWFsKGVycm9yU3RyaW5nLCAnJywgJ2BtYWluLmpzYCB0aWRhayBiZXJqYWxhbiBkZW5nYW4gc2VtZXN0aW55YS4gUGFzdGlrYW4ga2FtdSBtZW5naW1wb3IgZnVuZ3NpIGRhbiBjbGFzcyBkZW5nYW4gdGVwYXQuIE1pc2Fsa2FuLCBwYXN0aWthbiBrYW11IG1lbnVsaXNrYW4gZWtzdGVuc2kgYmVya2FzIC5qcyBrZXRpa2EgbWVuZ2ltcG9yIGRlbmdhbiBFU00uIFNpbWFrIGtlbWJhbGkgbWF0ZXJpICJodHRwczovL3d3dy5kaWNvZGluZy5jb20vYWNhZGVtaWVzLzYxMC90dXRvcmlhbHMvMzM1NzMiIEZvcm1hdCBTaXN0ZW0gTW9kdWxhcmlzYXNpIGRpIE5vZGUuanMgdW50dWsgbWVuZ2V0YWh1aSBjYXJhIG1lbmdpbXBvciBtb2R1bCBkZW5nYW4gRVNNLicpOwp9KSgpLmNhdGNoKChlcnJvcikgPT4gewogIGlmIChlcnJvci5uYW1lID09PSAnQXNzZXJ0aW9uRXJyb3InKSB7CiAgICBjb25zb2xlLmVycm9yKGVycm9yLm1lc3NhZ2UpOwogICAgcHJvY2Vzcy5leGl0KDEpOwogIH0gZWxzZSB7CiAgICBjb25zb2xlLmVycm9yKGBLYW1pIGdhZ2FsIG1lbmd1amkga29kZSB5YW5nIGthbXUgdHVsaXMuIEJlcmlrdXQgZXJyb3IgeWFuZyBkaWhhc2lsa2FuOiAke2Vycm9yLm1lc3NhZ2V9IFNpbWFrIGVycm9yIHRlcnNlYnV0IGRhbiBwYXN0aWthbiBrYW11IHN1ZGFoIG1lbnVsaXNrYW4ga29kZSBkZW5nYW4gYmVuYXIsIHlhIWApOwogICAgcHJvY2Vzcy5leGl0KDEpOwogIH0KfSk7Cg==';
    fs.writeFileSync(join(__dirname, 'main.test.js'), testingCode, 'base64');

    // write package.json to add "test" script
    const packageJsonCode = fs.readFileSync(join(__dirname, 'package.json'), 'utf-8');
    const currentPackageJson = JSON.parse(packageJsonCode);
    const newPackageJson = {
      ...currentPackageJson,
      scripts: {
        ...currentPackageJson.scripts,
        test: 'node main.test.js',
      },
    };

    fs.writeFileSync(join(__dirname, 'package.json'), JSON.stringify(newPackageJson, null, 2));

    try {
      execSync('npm test', { cwd: __dirname, stdio: 'pipe' });
      console.log('passed!');
    } catch (error) {
      const { stderr } = error;
      throw new Error(stderr.toString());
    } finally {
      fs.unlinkSync(join(__dirname, 'main.test.js'));
      fs.writeFileSync(join(__dirname, 'package.json'), packageJsonCode, 'utf-8');
    }
  } catch (error) {
    console.log(error.message);
  }
})();
